moviepj/movieapp/urls.py
from . import views
from django.contrib.auth import views as auth_views
from django.urls import path
app_name='movieapp'

urlpatterns = [
    path('', views.home,name='home'),
    path('profile/', views.profile,name='profile'),
    path('', views.just_registered,name='just_registered'),
    # path('add/', views.add, name='add'),
    # path('register/', views.register, name='register'),
    # path('login/', views.login, name='login'),
    # path('add/', views.add, name='add'),
    # path('logout/', views.logout, name='logout'),
    path('movie/<int:movie_id>/', views.detail, name='detail'),
    path('add/', views.add, name='add'),
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/', views.delete, name='delete'),
    path('search/', views.search, name='search'),
    path('register/',views.register,name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<slug:c_slug>/',views.moviecat,name='movies_by_category'),
    path('<slug:c_slug>/<slug:movies_slug>/',views.movdetail,name='movcatdetail'),

    path('',views.moviecat,name='moviecat'),
    path('<slug:c_slug>/',views.moviecat,name='movies_by_category'),
]

moviepj/moviepj/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls')),

]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,
                        document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

moviepj/templates/add.html
{% extends 'base.html' %}
{% block body %}






<section class="vh-100 bg-image">
  <div class="mask d-flex align-items-center h-100 gradient-custom-3">
    <div class="container h-100" >
      <div class="row d-flex justify-content-center align-items-center h-100" >
        <div class="col-12 col-md-9 col-lg-7 col-xl-6" >
          <div class="card" style="border-radius: 15px;" >
            <div class="card-body p-5"  style="background-color:#E0E0E0">
              <h2 class="text-uppercase text-center mb-5">Add Movie</h2>

<form method="POST" action="/add/" enctype="multipart/form-data">
    {%csrf_token%}

                <div class="form-outline mb-4">
                  <input type="text" name="name" class="form-control form-control-lg" />
                  <label class="form-label" name="name"> Name</label>
                </div>
              <div class="form-outline mb-4">
                  <input type="text" name="desc" class="form-control form-control-lg" />
                  <label class="form-label" name="desc">Description</label>
                </div>

                <div class="form-outline mb-4">
                  <input type="date" name="date" class="form-control form-control-lg" />
                  <label class="form-label"name="date">Date</label>
                </div>


                <div class="form-outline mb-4">
                  <input type="text" name="actors" class="form-control form-control-lg" />
                  <label class="form-label" name="actors"> Actors</label>
                </div>
                  <div class="form-outline mb-4">
<select name="category" class="custom-select mr-sm-2" id="inlineFormCustomSelect">
    {% for cat in category %}
    <option class="form-control form-control-lg" name="category" selected="selected" value="{{ cat.name }}">{{cat.name}}</option>
    <label class="form-label" name="category">Category</label>
    {% endfor %}
                </select></div>
                <div class="form-outline mb-4">
                  <input type="url" name="trailer" class="form-control form-control-lg" />
                  <label class="form-label" name="trailer">Trailer</label>
                </div>

                <div class="form-outline mb-4">
                  <input type="file" name="img" class="form-control form-control-lg" />
                  <label class="form-label" name="img">Poster</label>
                </div>



                <div class="d-flex justify-content-center">
                  <button type="submit"
                    class="btn btn-success btn-block btn-lg gradient-custom-4 text-body" >Add</button>
                </div>



              </form>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>












{% endblock %}

moviepj/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<script src="https://kit.fontawesome.com/1b99dd44bf.js"></script>
    <meta charset="UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"  >

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
<meta name="description" content="{% block metadescription %}{% endblock %}">


</head>
<body>

<nav class="navbar navbar-dark bg-dark" style="margin-bottom: 20px">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">
      online movie store
    </a>


          <form class="d-flex" action="{% url 'movieapp:search' %}" method="get">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search" name="q" aria-label="Search">
        <button class="btn btn-outline-success" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
      </form>

      <li class="nav-item dropdown" >
          <a style="color:#E0E0E0;margin-bottom:14px" class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            shop
          </a>
      <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'movieapp:moviecat' %}">all category</a></li>
              {% for i in links %}
            <li><a class="dropdown-item" href="/{{i.name}}" >{{i.name}}</a></li>
            {% endfor %}
          </ul>


      				{% if user.is_authenticated %}

<li><a href="/add" style="text-decoration: none;color:#E0E0E0">add</a></li>
<li >hello <a href="/profile" style="text-decoration: none;color:#E0E0E0">{{user.username}}</a></li>
      <li><a href="/logout" style="text-decoration: none;color:#E0E0E0">logout</a></li>
      {% else %}

      <li><a href="/register"style="text-decoration: none;color:#E0E0E0">register</a></li>

      <li><a href="/login" style="text-decoration: none;color:#E0E0E0">login</a></li>
      {% endif %}

</div>
 </nav>
{% block body %}
{% endblock %}
</body>
</html>

moviepj/templates/category.html
{% extends 'base.html' %}
{% block body %}
{% if category %}
<div>
    <div class="row my_row_class">
        <div class="mx-auto">
        <p><a href="{% url 'movieapp:moviecat' %}">our product collection</a> </p>
    </div></div>
</div>
{% endif %}
<div class="mx_auto">
    {% if category %}

</div>
<br>
<div>
    <h1 class="text-center my_title">{{category.name}}</h1>


</div>
{% else %}
<div>

</div>
<br>
<div>
    <h1 class="text-center my_title">our products collections</h1>
    <p class="text-justify">contrary to popular belief</p>
</div>

{% endif %}
<div class="container">
<div class="row mx_auto">
    {% for movie in movie.object_list %}
<div class="my_bottom_margin col-9 col-sm-12  col-md-4 xol-lg-4">
    <div class="card text-center" style="min-width:18rem;">
<a href="{{movie.get_url}}"><img src="{{movie.img.url}}" alt="{{movie.name}}" class="card-img-top my_image" width="200px" ></a>

<div class="card-body">

    <h4>{{movie.name}}</h4>
     <p>{{movie.date}}</p>
    </div>
</div>
</div>
{% endfor %}
</div>

    <br>
</div>
{% endblock%}

moviepj/templates/delete.html
<form method="post">
  {% csrf_token %}
  are you sure to delete this movie
  <input  type="submit">
</form>

moviepj/templates/detail.html
{% extends 'base.html' %}
{% block body %}

<div class="container" >
    <div class="row">

        <div class="col-md-6" >
            <img src="{{movie.img.url}}" width="250px" height="200px">
        </div>
        <div class="col-md-6">
            <h5 class="card-title">movie:{{movie.name}}</h5>
      <p class="card-text">description:{{movie.desc}}</p>
   <p class="card-text">actors:{{movie.actors}}</p>
       <p class="card-text">release date:{{movie.date}}</p>
       <p class="card-text">category:{{movie.category}}</p>
      <p class="card-text">trailer:<a href="{{movie.trailer}}">{{movie.trailer}}</a></p>
{% if request.user == movie.owner %}
        <a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">update</a>
        <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">delete</a>
{% endif %}
        </div>


    </div></div>

{% endblock %}

moviepj/templates/edit.html
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
{{form.as_p}}
    <input class="btn btn-success" type="submit">
</form>

moviepj/templates/home.html
{% extends 'base.html' %}
{% block body %}
<div  id="card" class="container" >
    <div class="row">
    {% for i in movielist %}
        <div class="col-md-4">
            <div class="card" style="width: 18rem;margin-bottom: 20px;margin-top: 20px;">
  <img  src="{{i.img.url}}" class="card-img-top" alt=" " width="250px" height="250px">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
      <p class="card-text">{{i.desc}}</p>
    <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">view details</a>

  </div>
            </div></div>{% endfor %}
    </div></div>
{% for user in users %}
{{user.name}}
{% endfor %}
{% endblock %}

moviepj/templates/login.html
{% extends 'base.html' %}
{% block body %}




<section class="vh-100">
  <div class="container-fluid h-custom">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-md-9 col-lg-6 col-xl-5">
        <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/draw2.webp"
          class="img-fluid" alt="Sample image">
      </div>
      <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
        <form  method="post" >
    {% csrf_token %}
          <div class="d-flex flex-row align-items-center justify-content-center justify-content-lg-start">
            <p class="lead fw-normal mb-0 me-3">Sign in with</p>
            <button type="button" class="btn btn-primary btn-floating mx-1">
              <i class="fab fa-facebook-f"></i>
            </button>

            <button type="button" class="btn btn-primary btn-floating mx-1">
              <i class="fab fa-twitter"></i>
            </button>

            <button type="button" class="btn btn-primary btn-floating mx-1">
              <i class="fab fa-linkedin-in"></i>
            </button>
          </div>

          <div class="divider d-flex align-items-center my-4">
            <p class="text-center fw-bold mx-3 mb-0">Or</p>
          </div>

          <!-- Email input -->
          <div class="form-outline mb-4">
            <input type="text" name="username" class="form-control form-control-lg"
              placeholder="Enter a valid email address" />
            <label class="form-label" name="username">Username</label>
          </div>

          <!-- Password input -->
          <div class="form-outline mb-3">
            <input type="password" name="password" class="form-control form-control-lg"
              placeholder="Enter password" />
            <label class="form-label" name="password">Password</label>
          </div>

          <div class="d-flex justify-content-between align-items-center">
            <!-- Checkbox -->
            <div class="form-check mb-0">
              <input class="form-check-input me-2" type="checkbox" value="" id="form2Example3" />
              <label class="form-check-label" for="form2Example3">
                Remember me
              </label>
            </div>
            <a href="#!" class="text-body">Forgot password?</a>
          </div>

          <div class="text-center text-lg-start mt-4 pt-2">
            <button type="submit" class="btn btn-primary">Login</button>

 <div> {% for i in messages %}
             <h4 style="color:red">{{i}}</h4>
             {% endfor %}</div>
            <p class="small fw-bold mt-2 pt-1 mb-0">Don't have an account? <a href="/register"
                class="link-danger">Register</a></p>

          </div>

        </form>
      </div>
    </div>
  </div>

    <!-- Copyright -->

    <!-- Right -->
<!--    <div>-->
<!--      <a href="#!" class="text-white me-4">-->
<!--        <i class="fab fa-facebook-f"></i>-->
<!--      </a>-->
<!--      <a href="#!" class="text-white me-4">-->
<!--        <i class="fab fa-twitter"></i>-->
<!--      </a>-->
<!--      <a href="#!" class="text-white me-4">-->
<!--        <i class="fab fa-google"></i>-->
<!--      </a>-->
<!--      <a href="#!" class="text-white">-->
<!--        <i class="fab fa-linkedin-in"></i>-->
<!--      </a>-->
<!--    </div>-->
    <!-- Right -->
  </div>
</section>











<div class="modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Modal title</h5>
        <button type="button" >
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Modal body text goes here.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}

moviepj/templates/profile.html
{% extends 'base.html' %}
{% block body %}
{% if user.is_authenticated %}
<div style="color:grey">
<h1>USER NAME:{{user.username}}</h1>
<h3>FIRST NAME:{{user.first_name}}</h3>
<h3>LAST NAME:{{user.last_name}}</h3>
<h3>EMAIL:{{user.email}}</h3></div>

{% endif %}
{% endblock %}

moviepj/templates/register.html
{% extends 'base.html' %}
{% block body %}

<!--     <input type="text" name="username" placeholder="username"><br>-->
<!--     <input type="text" name="first_name" placeholder="first name"><br>-->
<!--     <input type="text" name="last_name" placeholder="last name"><br>-->
<!--     <input type="email" name="email" placeholder="email"><br>-->
<!--     <input type="password" name="password" placeholder="password"><br>-->
<!--     <input type="password" name="password1" placeholder=" confirm password"><br><br>-->
<!--     <input type="submit"  onclick="myFunction()">-->





<section class="vh-100 bg-image">
  <div class="mask d-flex align-items-center h-100 gradient-custom-3">
    <div class="container h-100" >
      <div class="row d-flex justify-content-center align-items-center h-100" >
        <div class="col-12 col-md-9 col-lg-7 col-xl-6" >
          <div class="card" style="border-radius: 15px;" >
            <div class="card-body p-5"  style="background-color:#E0E0E0">
              <h2 class="text-uppercase text-center mb-5">Create an account</h2>

              <form  method="post">
{% csrf_token %}

                <div class="form-outline mb-4">
                  <input type="text" name="username" class="form-control form-control-lg" />
                  <label class="form-label" name="username">User Name</label>
                </div>
              <div class="form-outline mb-4">
                  <input type="text" name="first_name" class="form-control form-control-lg" />
                  <label class="form-label" name="first_name">First Name</label>
                </div>

                <div class="form-outline mb-4">
                  <input type="text" name="last_name" class="form-control form-control-lg" />
                  <label class="form-label"name="last_name">Last Name</label>
                </div>


                <div class="form-outline mb-4">
                  <input type="email" name="email" class="form-control form-control-lg" />
                  <label class="form-label" name="email"> Email</label>
                </div>

                <div class="form-outline mb-4">
                  <input type="password" name="password" class="form-control form-control-lg" />
                  <label class="form-label" name="password">Password</label>
                </div>

                <div class="form-outline mb-4">
                  <input type="password" name="password1" class="form-control form-control-lg" />
                  <label class="form-label" name="password1">Repeat your password</label>
                </div>

                <div class="form-check d-flex justify-content-center mb-5">
                  <input class="form-check-input me-2" type="checkbox" value="" id="form2Example3cg" />
                  <label class="form-check-label" for="form2Example3g">
                    I agree all statements in <a href="#!" class="text-body"><u>Terms of service</u></a>
                  </label>
                </div>
<div> {% for i in messages %}
             <h4 style="color:red">{{i}}</h4>
             {% endfor %}</div>
                <div class="d-flex justify-content-center">
                  <button type="submit"
                    class="btn btn-success btn-block btn-lg gradient-custom-4 text-body"  onclick="myFunction()">Register</button>
                </div>

                <p class="text-center text-muted mt-5 mb-0">Have already an account? <a href="/login"
                    class="fw-bold text-body"><u>Login here</u></a></p>

              </form>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>














<script>
function myFunction() {
  alert("successfully registered");
}
</script>
{% endblock %}

moviepj/templates/search.html
{% extends 'base.html' %}
{% block body %}
<div >
<p class="text-center my_text_search">you have searched for:<b>"{{query}}"</b></p>
    </div>
<div class="container">
<div class="row mx_auto">
    {% for movies in movie %}
<div class="my_bottom_margin col-9 col-sm-12  col-md-4 xol-lg-4">
    <div class="card text-center" style="min-width:18rem;">
<a href=""><img src="{{movies.img.url}}" alt="{{movies.name}}" class="card-img-top my_image" width="200px" ></a>

<div class="card-body">

    <h4>{{movies.name}}</h4>
     <p>{{movies.category}}</p>
    </div>
</div>

{% empty %}
<div class="row mx_auto">
<p class="text-center my_text_search">0 result found</p>
</div></div></div>
    <br><br><br><br><br><br><br>
{% endfor %}
</div>

{% endblock %}